// Generated by https://quicktype.io

class Business {
  List<NegocioData> items = new List();

  Business.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    //? Por cada item que recibe los va enviando al metodo que extrae los datos del json y retorna el mapa luego los agrega a una lista de items de tipo publicacion.
    for (var item in jsonList) {
      final negocio = new NegocioData.fromJsonMap(item);
      items.add(negocio);
    }
    // print(items[0]);
    // print(items.length);
    // print(items[0].apellidos);
  }
  get itemsList {
    return items;
  }
}

class NegocioData {
  String inicialNegocio;
  String ruc;
  String negocio;
  String telefono;
  String provincia;
  String canton;
  String ubicacion;
  List<dynamic> servicios;
  List<Personal> personal;
  List<PublicacionesNegocio> publicacionesNegocio;

  NegocioData({
    this.inicialNegocio,
    this.ruc,
    this.negocio,
    this.telefono,
    this.provincia,
    this.canton,
    this.ubicacion,
    this.servicios,
    this.personal,
    this.publicacionesNegocio,
  });

  NegocioData.fromJsonMap(Map<String, dynamic> json) {
    inicialNegocio = json ['inicial_negocio'];
    ruc = json ['ruc'];
    negocio = json ['negocio'];
    telefono = json ['telefono'];
    provincia = json ['provincia'];
    canton = json ['canton'];
    ubicacion = json ['ubicacion'];
    if(json['servicios'].length !=0){
      for(var item in json['servicios']){
        final serv = new ServiciosNegocio.fromJsonMap(item);
        servicios.add(serv);
      }
    }    
    if(json['personal'].length !=0){
      for(var item in json['personal']){
        final per = new Personal.fromJsonMap(item);
        personal.add(per);
      }
    }
    if(json['publicaciones_negocio'].length !=0){
      for(var item in json['publicaciones_negocio']){
        final pub = new PublicacionesNegocio.fromJsonMap(item);
        publicacionesNegocio.add(pub);
      }
    }
  }
get openInicialNegocio{
  if(inicialNegocio ==null){
    return'';
  }else{
    return inicialNegocio;
  }
}
get openRuc{
  if(ruc ==null){
    return'';
  }else{
    return ruc;
  }
}
get openNegocio{
  if(negocio ==null){
    return'';
  }else{
    return negocio;
  }
}
get openTelefono{
  if(telefono ==null){
    return'';
  }else{
    return telefono;
  }
}
get openProvincia{
  if(provincia ==null){
    return'';
  }else{
    return provincia;
  }
}
get openCanton{
  if(canton ==null){
    return'';
  }else{
    return canton;
  }
}
get openUbicacion{
  if(ubicacion ==null){
    return'';
  }else{
    return ubicacion;
  }
}
get openServicios{
  if(servicios ==null){
    return'';
  }else{
    return servicios;
  }
}
get openPersonal{
  if(personal ==null){
    return'';
  }else{
    return personal;
  }
}
get openPublicacionesNegocio{
  if(publicacionesNegocio ==null){
    return'';
  }else{
    return publicacionesNegocio;
  }
}
}

class Personal {
  String correoDoctor;
  String cedulaDoctor;
  String nombreDoctor;
  String rolDoctor;
  String profesionDoctor;
  String celularDoctor;
  String sexoDoctor;
  String fotoPerfil;

  Personal({
    this.correoDoctor,
    this.cedulaDoctor,
    this.nombreDoctor,
    this.rolDoctor,
    this.profesionDoctor,
    this.celularDoctor,
    this.sexoDoctor,
    this.fotoPerfil,
  });
  Personal.fromJsonMap(Map<String, dynamic> json) {
    correoDoctor = json['correo_doctor'];
    cedulaDoctor = json['cedula_doctor'];
    nombreDoctor = json['nombre_doctor'];
    rolDoctor = json['rol_doctor'];
    profesionDoctor = json['profesion_doctor'];
    celularDoctor = json['celular_doctor'];
    sexoDoctor = json['sexo_doctor'];
    fotoPerfil = json['foto_perfil'];
  }
}

class PublicacionesNegocio {
  String idPublicacion;
  PublicacionesNegocio({
    this.idPublicacion,
  });
  PublicacionesNegocio.fromJsonMap(Map<String, dynamic> json) {
    idPublicacion = json['id_publicacion'];
  }
}

class ServiciosNegocio {
  String idServicio;
  ServiciosNegocio({
    this.idServicio,
  });
  ServiciosNegocio.fromJsonMap(Map<String, dynamic> json) {
    idServicio = json['id_servicio'];
  }
}
