// Generated by https://quicktype.io

class Business {
  List<NegocioData> items = new List();

  Business.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    //? Por cada item que recibe los va enviando al metodo que extrae los datos del json y retorna el mapa luego los agrega a una lista de items de tipo publicacion.
    for (var item in jsonList) {
      final negocio = new NegocioData.fromJsonMap(item);
      print(negocio);
      items.add(negocio);
    }
    // print(items[0]);
    // print(items.length);
    // print(items[0].apellidos);
  }
  
  get itemsList {
    return items;
  }
}

class NegocioData {
  String inicialNegocio;
  String ruc;
  String negocio;
  String telefono;
  String provincia;
  String canton;
  String ubicacion;
  String foto;
  List<ServiciosNegocio> servicios = new List();
  List<Personal> personal = new List();
  List<PublicacionesNegocio> publicacionesNegocio = new List();
  double latitud;
  double longitud;

  NegocioData({
    this.inicialNegocio,
    this.ruc,
    this.negocio,
    this.telefono,
    this.provincia,
    this.canton,
    this.ubicacion,
    this.foto,
    this.servicios,
    this.personal,
    this.publicacionesNegocio,
    this.latitud,
    this.longitud,
  });

  NegocioData.fromJsonMap(Map<String, dynamic> json) {
    try {
      inicialNegocio = json['inicial_negocio'];
      ruc = json['ruc'];
      negocio = json['negocio'];
      telefono = json['telefono'];
      provincia = json['provincia'];
      canton = json['canton'];
      ubicacion = json['ubicacion'];
      latitud=double.parse(json['latitud']);
      longitud=double.parse(json['longitud']);
      foto = json['foto'];
      if (json['servicios'].length != 0) {
        for (var item in json['servicios']) {
          final serv = new ServiciosNegocio.fromJsonMap(item);
          servicios.add(serv);
        }
      }
      if (json['personal'].length != 0) {
        for (var item in json['personal']) {
          final per = new Personal.fromJsonMap(item);
          personal.add(per);
        }
      }
      if (json['publicaciones_negocio'].length != 0) {
        for (var item in json['publicaciones_negocio']) {
          final pub = new PublicacionesNegocio.fromJsonMap(item);
          publicacionesNegocio.add(pub);
        }
      }
    } catch (e) {
      print(e);
    }
  }
  get openInicialNegocio {
    if (inicialNegocio == null) {
      return '';
    } else {
      return inicialNegocio;
    }
  }

  get openRuc {
    if (ruc == null) {
      return '';
    } else {
      return ruc;
    }
  }

  get openNegocio {
    if (negocio == null) {
      return '';
    } else {
      return negocio;
    }
  }

  get openTelefono {
    if (telefono == null) {
      return '';
    } else {
      return telefono;
    }
  }

  get openProvincia {
    if (provincia == null) {
      return '';
    } else {
      return provincia;
    }
  }

  get openCanton {
    if (canton == null) {
      return '';
    } else {
      return canton;
    }
  }

  get openUbicacion {
    if (ubicacion == null) {
      return '';
    } else {
      return ubicacion;
    }
  }

  get openServicios {
    if (servicios == null) {
      return [];
    } else {
      return servicios;
    }
  }

  get openPersonal {
    if (personal == null) {
      return '';
    } else {
      return personal;
    }
  }

  get openPublicacionesNegocio {
    return publicacionesNegocio;
  }
}

class Personal {
  String correoDoctor;
  String cedulaDoctor;
  String nombreDoctor;
  String rolDoctor;
  String profesionDoctor;
  String celularDoctor;
  String sexoDoctor;
  String fotoPerfil;

  Personal({
    this.correoDoctor,
    this.cedulaDoctor,
    this.nombreDoctor,
    this.rolDoctor,
    this.profesionDoctor,
    this.celularDoctor,
    this.sexoDoctor,
    this.fotoPerfil,
  });
  Personal.fromJsonMap(Map<String, dynamic> json) {
    correoDoctor = json['correo_doctor'];
    cedulaDoctor = json['cedula_doctor'];
    nombreDoctor = json['nombre_doctor'];
    rolDoctor = json['rol_doctor'];
    profesionDoctor = json['profesion_doctor'];
    celularDoctor = json['celular_doctor'];
    sexoDoctor = json['sexo_doctor'];
    fotoPerfil = json['foto_perfil'];
  }
}

class PublicacionesNegocio {
  String idPublicacion;
  PublicacionesNegocio({
    this.idPublicacion,
  });
  PublicacionesNegocio.fromJsonMap(Map<String, dynamic> json) {
    idPublicacion = json['id_publicacion'];
  }
}

class ServiciosDoctorNegocio {
  List<ServiciosNegocio> items = new List();

  ServiciosDoctorNegocio.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    for (var item in jsonList) {
      final servicio = new ServiciosNegocio.fromJsonMap(item);
      items.add(servicio);
    }
  }
}

class ServiciosNegocio {
  String idServicio;
  String servicio;
  String duracion;
  String imagenServicio;
  String rucNegocio;
  String nombreNegocio;
  String fotoNegocio;
  String telefonoNegocio;
  List<PreguntasServicios> preguntas = new List();

  ServiciosNegocio({
    this.idServicio,
    this.servicio,
    this.duracion,
    this.imagenServicio,
    this.nombreNegocio,
    this.rucNegocio,
    this.fotoNegocio,
    this.telefonoNegocio,
  });
  ServiciosNegocio.fromJsonMap(Map<String, dynamic> json) {
    idServicio = json['id_servicio'];
    servicio = json['descripcion'];
    duracion = json['duracion'];
    imagenServicio = json['imagen_servicio'];
    rucNegocio = json['ruc_negocio'];
    nombreNegocio = json['nombre_negocio'];
    fotoNegocio = json['foto_negocio'];
    telefonoNegocio = json['telefono_negocio'];
    if(json.containsKey('preguntas_frecuentes')){
      if (json['preguntas_frecuentes'].length != 0) {
      for (var item in json['preguntas_frecuentes']) {
        final preg = new PreguntasServicios.fromJsonMap(item);
        preguntas.add(preg);
      }
    }
    }
    
  }
}

class PreguntasServicios {
  PreguntasServicios({
    this.preguntasFrecuenteId,
    this.descripcion,
    this.respuesta,
  });

  String preguntasFrecuenteId;
  String descripcion;
  String respuesta;

  PreguntasServicios.fromJsonMap(Map<String, dynamic> json) {
    preguntasFrecuenteId = json["frequent_questions_id"];
    descripcion = json["frequent_questions_description"];
    respuesta = json["frequent_questions_reply"];
  }
}
