// Generated by https://quicktype.io

class BusinessDataGps {
  List<NegocioDataGps> items = new List();
  BusinessDataGps.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    //? Por cada item que recibe los va enviando al metodo que extrae los datos del json y retorna el mapa luego los agrega a una lista de items de tipo publicacion.
    for (var item in jsonList) {
      final negocio = new NegocioDataGps.fromJsonMap(item);
      print(negocio);
      items.add(negocio);
    }
    // print(items[0]);
    // print(items.length);
    // print(items[0].apellidos);
  }

}

class NegocioDataGps {
  String inicialNegocio;
  String ruc;
  String negocio;
  String telefono;
  String provincia;
  String canton;
  String ubicacion;
  String foto;
  double longitud;
  double latitud;

  NegocioDataGps({
    this.inicialNegocio,
    this.ruc,
    this.negocio,
    this.telefono,
    this.provincia,
    this.canton,
    this.ubicacion,
    this.foto,
    this.longitud,
    this.latitud,
  });
  NegocioDataGps.fromJsonMap(Map<String, dynamic> json) {
    try {
      inicialNegocio = json['inicial_negocio'];
      ruc = json['ruc'];
      negocio = json['negocio'];
      telefono = json['telefono'];
      provincia = json['provincia'];
      canton = json['canton'];
      ubicacion = json['ubicacion'];
      latitud=double.parse(json['latitud']);
      longitud=double.parse(json['longitud']);
      foto = json['foto'];
    } catch (e) {
      print(e);
    }
  }

  
}

