// Generated by https://quicktype.io

import 'package:muro_dentcloud/src/models/business_Services_models.dart';

class Follow {
  List<Siguiendo> items = new List();

  Follow.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    for (var item in jsonList) {
      final follow = new Siguiendo.fromJsonMap(item);
      items.add(follow);
      print(follow);
    }
  }
}

class Siguiendo {
  List<UsuariosSeguido> usuariosSeguidos = new List();
  List<NegociosSeguido> negociosSeguidos = new List();

  Siguiendo({
    this.usuariosSeguidos = const [],
    this.negociosSeguidos = const [],
  });
  Siguiendo.fromJsonMap(Map<String, dynamic> json) {
    if (json['usuarios_seguidos'].length != 0) {
      for (var item in json['usuarios_seguidos']) {
        final sig = new UsuariosSeguido.fromJsonMap(item);
        usuariosSeguidos.add(sig);
      }
    }
    if (json['negocios_seguidos'].length != 0) {
      for (var item in json['negocios_seguidos']) {
        final neg = new NegociosSeguido.fromJsonMap(item);
        negociosSeguidos.add(neg);
      }
    }
  }
}

class NegociosSeguido {
  String idNegocioSiguiendo;
  String negocioSeguido;
  String fechaSeguimiento;
  String fotoNegocio;
  String nombreNegocio;

  NegociosSeguido(
      {this.idNegocioSiguiendo,
      this.negocioSeguido,
      this.fechaSeguimiento,
      this.fotoNegocio,
      this.nombreNegocio});
  NegociosSeguido.fromJsonMap(Map<String, dynamic> json) {
    idNegocioSiguiendo = json['id_negocio_siguiendo'];
    negocioSeguido = json['negocio_seguido'];
    fechaSeguimiento = json['fecha_seguimiento'];
    fotoNegocio = json['foto_negocio'];
    nombreNegocio = json['nombre_negocio'];
  }
}

class UsuariosSeguido {
  String idUsuarioSiguiendo;
  String usuarioSeguido;
  String fechaSeguimiento;
  String nombreUsuario;
  String fotoPerfil;

  UsuariosSeguido({
    this.idUsuarioSiguiendo,
    this.usuarioSeguido,
    this.fechaSeguimiento,
    this.fotoPerfil,
    this.nombreUsuario
  });
  UsuariosSeguido.fromJsonMap(Map<String, dynamic> json) {
    idUsuarioSiguiendo = json['id_usuario_siguiendo'];
    usuarioSeguido = json['usuario_seguido'];
    fechaSeguimiento = json['fecha_seguimiento'];
    fotoPerfil= json['foto_perfil'];
    nombreUsuario= json['nombre_usuario'];
  }
}
