// Generated by https://quicktype.io

class Logins {
  //? Lista de tipo publicacion donde se almacenaran los datos extraidos.
  List<Login> items = new List();

  // Publicaciones()

  Logins.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    //? Por cada item que recibe los va enviando al metodo que extrae los datos del json y retorna el mapa luego los agrega a una lista de items de tipo publicacion.
    for (var item in jsonList) {
      final login = new Login.fromJsonMap(item);
      items.add(login);
    }
  }
}

class Login {
  // String jsontype;
  // List<RespuestaObtenida> respuestaObtenida;
  String message;

  Login({
    // this.jsontype,
    // this.respuestaObtenida,
    this.message,
  });
  Login.fromJsonMap(Map<String, dynamic> json) {
    print(json);
    // jsontype = json['jsontype'];
    message = json['message'];
    // respuestaObtenida = json['respuesta_obtenida'];
    // respuestaObtenida[0].message = json['respuesta_optenida[0].message'];
  }

  bool getLogin() {
    bool resp = false;
    if (message == "Ingreso Correcto") {
      return resp = true;
    } else {
      return resp;
    }
  }
}

class RespuestaObtenida {
  String message;

  RespuestaObtenida({
    this.message,
  });
}
