// Generated by https://quicktype.io
class Logins {
  List<Login> items = new List();

  Logins.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    for (var item in jsonList) {
      final login = new Login.fromJsonMap(item);
      items.add(login);
    }
  }
}

class Login {
  String message;

  Login({
    this.message,
  });

  Login.fromJsonMap(Map<String, dynamic> json) {
    message = json['message'];
  }

  getLogin() {
    if (message == null) {
      return 'HUBO UN PROBLEMA EN EL INICIO DE SESION';
    }
    if (message == 'INGRESO CORRECTO') {
      return 'Inicio de Sesion Exitoso.!!';
    }
    if (message == 'CONTRASEÑA INCORRECTA') {
      return 'Usuario o Contraseña Incorrectos.!!';
    }
    if (message == 'NO EXISTE EL CORREO') {
      return 'Usuario o Contraseña Incorrectos.!!';
    }
  }
}
