// Generated by https://quicktype.io
class Publicaciones {
  List<Publicacion> items = new List();

  Publicaciones();

  Publicaciones.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final publicacion = new Publicacion.fromJsonMap(item);
      items.add(publicacion);
    }
  }
}

class Publicacion {
  String usuario;
  String descripcion;
  String archivo;
  String fecha;
  String negocio;

  Publicacion({
    this.usuario,
    this.descripcion,
    this.fecha,
    this.archivo,
    this.negocio,
  });
  //? /1 Para connvertir a double y .cast<int>() para lista de items
  Publicacion.fromJsonMap(Map<String, dynamic> json) {
    usuario      = json['usuario'];
    descripcion  = json['descripcion'];
    archivo      = json['archivo'];
    fecha        = json['fecha'];
    negocio      = json['negocio'];
  }
}
