// Generated by https://quicktype.io

class Publicaciones {
  String usuario;
  String descripcion;
  String archivo;
  String fecha;
  String negocio;

  Publicaciones({
    this.usuario,
    this.descripcion,
    this.fecha,
    this.archivo,
    this.negocio,
  });

  Publicaciones.fromJsonMap(Map<String, dynamic> json) {
    usuario     = json['usuario'];
    descripcion = json['descripcion'];
    fecha       = json['fecha'];
    archivo     = json['archivo'];
    negocio     = json['negocio'];
  }
}
