// Generated by https://quicktype.io
class BusinesData {
  List<Negocio> items = new List();
  BusinesData.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    //? Por cada item que recibe los va enviando al metodo que extrae los datos del json y retorna el mapa luego los agrega a una lista de items de tipo publicacion.
    for (var item in jsonList) {
      final publicacion = new Negocio.fromJsonMap(item);
      items.add(publicacion);
      // print(publicacion.comentarios.length);
    }
  }
}

class Negocio {
  String rucNegocio;
  String nombreNegocio;
  String telefonoNegocio;
  String provincia;
  String canton;
  String direccionNegocio;
  String fotoNegocio;

  Negocio({
    this.rucNegocio,
    this.nombreNegocio,
    this.telefonoNegocio,
    this.provincia,
    this.canton,
    this.direccionNegocio,
    this.fotoNegocio,
  });
  Negocio.fromJsonMap(Map<String, dynamic> json) {
   rucNegocio = json['ruc_negocio'];
   nombreNegocio = json['nombre_negocio'];
   telefonoNegocio = json['telefono_negocio'];
   provincia = json['provincia'];
    canton = json['canton'];
    direccionNegocio = json['direccion_negocio'];
    fotoNegocio = json['foto_negocio'];
  }
}


