// Generated by https://quicktype.io

class ContactoData {
  String jsontype;
  List<ContactoElement> items = new List();
  ContactoData.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    //? Por cada item que recibe los va enviando al metodo que extrae los datos del json y retorna el mapa luego los agrega a una lista de items de tipo publicacion.
    for (var item in jsonList) {
      final publicacion = new ContactoElement.fromJsonMap(item);
      items.add(publicacion);
      // print(publicacion.comentarios.length);
    }
  }
 
}

class ContactoElement {
  String emailContacto;
  String nombreContacto;
  String celularContacto;
  String sexoContacto;
  String cedulaContacto;
  DateTime nacimientoContacto;
  String provinciaContacto;
  String ciudadContacto;
  String fotoPerfilContacto;

  ContactoElement({
    this.emailContacto,
    this.nombreContacto,
    this.celularContacto,
    this.sexoContacto,
    this.cedulaContacto,
    this.nacimientoContacto,
    this.provinciaContacto,
    this.ciudadContacto,
    this.fotoPerfilContacto,
  });
 ContactoElement.fromJsonMap(Map<String, dynamic> json) {
   emailContacto=json['email_contacto'];
   nombreContacto=json['nombre_contacto'];
   cedulaContacto=json['celular_contacto'];
   sexoContacto=json['sexo_contacto'];
   cedulaContacto=json['cedula_contacto'];
   nacimientoContacto=DateTime.parse(json['nacimiento_contacto']);
   provinciaContacto=json['provincia_contacto'];
   ciudadContacto=json['ciudad_contacto'];
   fotoPerfilContacto=json['foto_perfil_contacto'];
  }


}
