// Generated by https://quicktype.io

class DoctorDataPrincipal {
  List<DoctorDato> items = new List();
  DoctorDataPrincipal.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    //? Por cada item que recibe los va enviando al metodo que extrae los datos del json y retorna el mapa luego los agrega a una lista de items de tipo publicacion.
    for (var item in jsonList) {
      final publicacion = new DoctorDato.fromJsonMap(item);
      items.add(publicacion);
      // print(publicacion.comentarios.length);
    }
  }

  
}

class DoctorDato {
  String doctor;
  String correo;
  String cedula;
  String fechaNacimiento;
  String celular;
  String sexo;
  String fotoPerfil;
  String  profesion;

  DoctorDato({
    this.doctor,
    this.correo,
    this.cedula,
    this.fechaNacimiento,
    this.celular,
    this.sexo,
    this.fotoPerfil,
    this.profesion,
  });
   DoctorDato.fromJsonMap(Map<String, dynamic> json) {
   doctor=json['doctor'];
   correo=json['correo'];
   cedula=json['cedula'];
   fechaNacimiento=json['fecha_nacimiento'];
   celular=json['celular'];
   sexo=json['sexo'];
   fotoPerfil=json['foto_perfil'];
   profesion=json['profesion'];
  }

}




