// Generated by https://quicktype.io
class UserDatas {
List<UserData> items = new List();
UserDatas.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    //? Por cada item que recibe los va enviando al metodo que extrae los datos del json y retorna el mapa luego los agrega a una lista de items de tipo publicacion.
    for (var item in jsonList) {
      final publicacion = new UserData.fromJsonMap(item);
      items.add(publicacion);
      // print(publicacion.comentarios.length);
    }
  }

}


class UserData{
  String emailUsuario;
  String nombreUsuario;
  String cedulaUsuario;
  String nacimientoUsuario;
  String celularUsuario;
  String sexoUsuario;
  String tipoUsuario;
  String provinciaUsuario;
  String ciudadUsuario;
  String fotoPerfilUsuario;
  UserData({
    this.emailUsuario,
    this.nombreUsuario,
    this.cedulaUsuario,
    this.nacimientoUsuario,
    this.celularUsuario,
    this.sexoUsuario,
    this.provinciaUsuario,
    this.tipoUsuario,
    this.ciudadUsuario,
    this.fotoPerfilUsuario
  });
  UserData.fromJsonMap(Map<String, dynamic> json) {
   emailUsuario = json['email_usuario'];
   nombreUsuario = json['nombre_usuario'];
   cedulaUsuario = json['cedula_usuario'];
   nacimientoUsuario = json['nacimiento_usuario'];
    celularUsuario = json['celular_usuario'];
    sexoUsuario = json['sexo_usuario'];
    provinciaUsuario = json['provincia_usuario'];
    tipoUsuario = json['tipo_usuario'];
    ciudadUsuario = json['ciudad_usuario'];
    fotoPerfilUsuario= json['foto_perfil_usuario'];
  }

}
